### ISSUE TITLE
TEA => Math in titles doesn't render correctly

### ISSUE THREAD

**Issue by tomjw64** [Connexions/cnx-recipes#326]
![screenshot_37](https://user-images.githubusercontent.com/1285308/30222259-3c997924-948c-11e7-872b-789cb07a0d0b.png)

![screenshot_38](https://user-images.githubusercontent.com/1285308/30222267-424ac652-948c-11e7-897b-962373a5edbc.png)

**Comment by rfreedholm** [comment]
MathJax uses a lot of markup which the field in the database cannot handle (it is limited to 255). For now, the solution we have implemented is to display the title up to the point of math output and than append an ellipsis. At this time, implementing a solution to accommodate the markup would more dev hours than we have allotted to this project (in fact, we are already significantly over). 
With the current solution, you can edit the titles after the import.  From my understanding, this issue only affects these two titles, so that is likely the most efficient route to take. If we need to consult with the TEA on this, we can.
