### ISSUE TITLE
Figures aren't numbered in the preface

### ISSUE THREAD

**Issue by helenemccarron** [Connexions/cnx-recipes#455]
Numbering for figures and tables isn't currently working in prefaces.

**Comment by openstaxalina** [comment]
@lwtchu please review and prioritize (Did we decide to support this in PDF?  We should make a consistent decision for webview.)

**Comment by lwtchu** [comment]
It's supported in the PDF.

**Comment by damondemar** [comment]
addressed in pr #453

**Comment by Stackblocks** [comment]
Displaying as specified with updated version of content / code.

![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/71f7f781-15bc-42ed-a625-76b794f11091)

**Comment by wilkus27** [comment]
@openstaxalina I am not sure what does it mean that this flag is supported in PDF. It means that when figures/tables are not numbered in pdf, they shouldn't be numbered on webview or it means that all figures/tables from Preface after turning on this flag should be numbered on webview and when in PDF they are not, this numbering will be added there? 

I am asking because after turning on flags appear two situations:

1) In Biology 2e (https://staging.cnx.org/contents/jVCgr5SL@15.1:2zYFPFKB@13/Preface) figures in PDF are not numbered:

![biology_2e_pdf](https://user-images.githubusercontent.com/40228854/45211541-dd25a000-b292-11e8-8209-62205234f3e8.JPG)

but on webview now they are:

![biology_2e](https://user-images.githubusercontent.com/40228854/45211561-eb73bc00-b292-11e8-8562-663962897490.JPG)

2. In Biology for AP Courses (https://staging.cnx.org/contents/bDIuMp-w@9.1:Hd4bYWPU@7/Preface) there are tables which are not numbered on webview and they are also not numbered in PDF.

I created an issue about it https://github.com/Connexions/cnx-recipes/issues/601, but you closed it. 

So should I create an issue about situation from Biology 2e?

**Comment by openstaxalina** [comment]
Hi @wilkus27, thank you for asking this question.  The flag means that the webview & PDF **should match** in terms of numbering in the preface.  Do you think we could catalog places where the webview & PDF do not match in this issue? We can likely resolve these with new tagging in the content.

I closed #601 because the PDF & webview already match (no numbering in either format) for AP Biology.

**Comment by wilkus27** [comment]
@openstaxalina I think we could, should I create an issue on GitHub or some document for that?

**Comment by openstaxalina** [comment]
@wilkus27 could we use this issue and add labels for any book where the numbering in the PDF & webview doesn't match?

**Comment by wilkus27** [comment]
@openstaxalina Ok, so I reopen it.

**Comment by wilkus27** [comment]
**Principles of Microeconomics 2e** (https://staging.cnx.org/contents/XAl2LLVA@9.1:Vqc2J7Te@12/Preface)

webview:

![micro_2e](https://user-images.githubusercontent.com/40228854/45228366-4de4b080-b2c3-11e8-9386-933c6fb6a5ee.JPG)

PDF:

![micro_2e_pdf](https://user-images.githubusercontent.com/40228854/45228386-56d58200-b2c3-11e8-8023-dbbc09641a8d.JPG)

**Comment by wilkus27** [comment]
**Principles of Macroeconomics 2e** (https://staging.cnx.org/contents/J_WQZJkO@6.1:a3dFfRuk@6/Preface)

webview:

![macro_2e](https://user-images.githubusercontent.com/40228854/45228828-8769eb80-b2c4-11e8-9d48-0cb4ae6b8a54.JPG)

PDF:

![macro_2e_pdf](https://user-images.githubusercontent.com/40228854/45228850-918bea00-b2c4-11e8-9adb-844af25098d1.JPG)

**Comment by wilkus27** [comment]
**Principles of Microeconomics for AP® Courses 2e** (https://staging.cnx.org/contents/Y2y_2U43@4.1:DFElNw5s@4/Preface) 

webview:

![micro_2e_ap](https://user-images.githubusercontent.com/40228854/45298894-2a5f7700-b50a-11e8-8513-a32dcca1b2b9.JPG)

PDF:

![micro_2e_ap_pdf](https://user-images.githubusercontent.com/40228854/45298908-35b2a280-b50a-11e8-903a-0206f37ead9a.JPG)

**Comment by wilkus27** [comment]
@openstaxalina These are all books where webview and PDF are inconsistant in Preface.

**Comment by openstaxalina** [comment]
@wilkus27 thank you!  moving this to content.

**Comment by openstaxalina** [comment]
Issue moved to [Connexions/content-managers #307](https://github.com/Connexions/content-managers/issues/307) via [**ZenHub**](https://www.zenhub.com/)
