### ISSUE TITLE
Missing term in index

### ISSUE THREAD

**Issue by wilkus27** [Connexions/cnx-recipes#464]
In Index (https://devb.cnx.org/contents/tWu56V64@33.86:BK2Pfetd@33.86/Index) link to the term is in improper place:
![term_devb](https://user-images.githubusercontent.com/40228854/42624050-ba4a2880-85c4-11e8-9960-ee617524fbbd.JPG)

This is how it looks in pdf:
![term_pdf](https://user-images.githubusercontent.com/40228854/42624133-f3ccc57c-85c4-11e8-9f0b-e168701c33df.JPG)

**Comment by openstaxalina** [comment]
I think we should re-test this after the content refresh.  This looks very strange to me.

**Comment by PatBoj** [comment]
This bug occurs when we're trying to set single letter as a term. I tried to put in the raw `.html` file single letter `t` as a term and it also created this issue. I am wondering if it's a content issue, because single letter in the index tells us nothing. In my opinion, it should be `population proportion p` instead of just single `p`. What do you think @openstaxalina?

**Comment by openstaxalina** [comment]
I will investigate this with Anthony.  The terms are:
Parental Generation (Concepts of Biology)
<img width="818" alt="screen shot 2018-08-08 at 12 49 41 pm" src="https://user-images.githubusercontent.com/7863733/43854876-bc27a416-9b09-11e8-9f17-c9b6a744ee5b.png">
Population Proportion (Intro Biz Stats)
<img width="1090" alt="screen shot 2018-08-08 at 12 50 45 pm" src="https://user-images.githubusercontent.com/7863733/43854881-bf721520-9b09-11e8-90a5-4ac95fae5dc8.png">

**Comment by helenemccarron** [comment]
Just out of curiosity, @reedstrm, what are your thoughts on this one?

**Comment by openstaxalina** [comment]
Issue moved to [Connexions/content-managers #225](https://github.com/Connexions/content-managers/issues/225) via [**ZenHub**](https://www.zenhub.com/)
