### ISSUE TITLE
Business Ethics - Index page number color contrast

### ISSUE THREAD

**Issue by mwest-WWprod** [Connexions/cnx-recipes#513]
content01
GLOBAL

For the color contrast to pass AA requirements, the text must be 14pts or larger. It appears as though Index accent color used for **page numbers** do not currently pass the AA requirements.

![hyperlinks_index color contrast](https://user-images.githubusercontent.com/19212926/43348786-d6c49e58-91c9-11e8-95f8-d33aa81868b0.png)

![hyperlinks_index color contrast checker](https://user-images.githubusercontent.com/19212926/43348791-da546d50-91c9-11e8-8813-8e3c37739f91.png)

**Comment by openstaxalina** [comment]
I believe this issue is in the PDF; the below screenshot is from webview:
<img width="493" alt="screen shot 2018-07-29 at 12 38 07 pm" src="https://user-images.githubusercontent.com/7863733/43369030-496dd826-932c-11e8-9d62-0bccdf472f26.png">

@Stackblocks, could you please transfer this issue to oer.exports?
cc @mwest-WWprod

**Comment by brittweinstein** [comment]
Issue moved to [Connexions/oer.exports #3728](https://github.com/Connexions/oer.exports/issues/3728) via [**ZenHub**](https://www.zenhub.com/)
