### ISSUE TITLE
Grey caption in table

### ISSUE THREAD

**Issue by openstaxalina** [Connexions/cnx-recipes#573]
@wilkus27 commented on [Thu Aug 23 2018](https://github.com/Connexions/content-managers/issues/252)

On katalyst01 (https://katalyst01.cnx.org/contents/MBiUQmmY@20.1:0jV_L6-5@20.1/Bringing-It-Together-Homework) there is a table with grey caption inside. It should be next to the numbering.

katalyst01:

![grey_cap](https://user-images.githubusercontent.com/40228854/44510514-2e3f6c80-a6b5-11e8-894f-eccfe4c6a574.JPG)

PDF:

![grey_cap_pdf](https://user-images.githubusercontent.com/40228854/44510528-35667a80-a6b5-11e8-8ad7-00223521edc4.JPG)

**Comment by openstaxalina** [comment]
@wilkus27 I moved this to the cnx-recipes repo.  I think this needs dev analysis before we make this a content-managers issue.

**Comment by PatBoj** [comment]
@openstaxalina I'm almost sure that is a content issue, because every, properly displayed caption in the book has `span` container with `data-type="title"` in raw (not baked) html file. I've got some examples:

## ***Wrong:***
![image](https://user-images.githubusercontent.com/20907906/44572304-bbe98d80-a783-11e8-95a0-9cc09f0cf9a4.png)
![image](https://user-images.githubusercontent.com/20907906/44572307-bdb35100-a783-11e8-8391-144916eb54cd.png)

## ***Right:***
### Example 1:
![image](https://user-images.githubusercontent.com/20907906/44572317-c73cb900-a783-11e8-8450-28e7fd979f5d.png)
![image](https://user-images.githubusercontent.com/20907906/44572322-c9067c80-a783-11e8-89d2-a7c107bce9d3.png)

### Example 2:
![image](https://user-images.githubusercontent.com/20907906/44572332-ce63c700-a783-11e8-9453-3eac897cb3ac.png)
![image](https://user-images.githubusercontent.com/20907906/44572335-d02d8a80-a783-11e8-9f55-bf9455060c83.png)

**Comment by openstaxalina** [comment]
Issue moved to [Connexions/content-managers #267](https://github.com/Connexions/content-managers/issues/267) via [**ZenHub**](https://www.zenhub.com/)
