### ISSUE TITLE
Middle of the equation in block

### ISSUE THREAD

**Issue by openstaxalina** [Connexions/cnx-recipes#574]
@wilkus27 commented on [Thu Aug 23 2018](https://github.com/Connexions/content-managers/issues/253)

On katalyst01 (https://katalyst01.cnx.org/contents/MBiUQmmY@20.1:z5OiUaGM@20.1/Solutions) in one of the in-line equation its middle displays in block. This problem doesn't occur in pdf.

katalyst01:

![block](https://user-images.githubusercontent.com/40228854/44512128-df480600-a6b9-11e8-8331-6d904c0c9e55.JPG)

PDF:

![block_pdf](https://user-images.githubusercontent.com/40228854/44512139-e707aa80-a6b9-11e8-8414-e2a84a7f1de6.JPG)

**Comment by openstaxalina** [comment]
@wilkus27 I moved this to the cnx-recipes repo. I think this needs dev analysis before we make this a content-managers issue.

**Comment by openstaxalina** [comment]
@wilkus27 I moved this to the cnx-recipes repo. I think this needs dev analysis before we make this a content-managers issue.

**Comment by PiotrKozlowski** [comment]
@openstaxalina I believe this is same issue as `https://github.com/Connexions/content-managers/issues/215`

**Comment by PatBoj** [comment]
@openstaxalina It is definitely content, because the equal sight is outside the math, and the fraction `4, 464/16,900` displays as `block` when other math elements display as `inline`. Screens from raw (not baked) html below:
![image](https://user-images.githubusercontent.com/20907906/44577515-9c596180-a791-11e8-90a2-5074ad6d9c46.png)
![image](https://user-images.githubusercontent.com/20907906/44577518-9e232500-a791-11e8-96cf-8dd7e1589d39.png)

**Comment by openstaxalina** [comment]
Issue moved to [Connexions/content-managers #266](https://github.com/Connexions/content-managers/issues/266) via [**ZenHub**](https://www.zenhub.com/)
