### ISSUE TITLE
Note without header

### ISSUE THREAD

**Issue by openstaxalina** [Connexions/cnx-recipes#575]
@wilkus27 commented on [Thu Aug 23 2018](https://github.com/Connexions/content-managers/issues/254)

In PDF there is note without header:

![note_pdf](https://user-images.githubusercontent.com/40228854/44527946-99eefd00-a6e8-11e8-9264-d7e3000b662a.JPG)

On katalyst01 (https://katalyst01.cnx.org/contents/MBiUQmmY@20.1:kDUE7w38@13/5-2-The-Uniform-Distribution -> **Example 5.4**) note have header but it is not styled like another ones:

![note](https://user-images.githubusercontent.com/40228854/44528032-d4f13080-a6e8-11e8-98b0-dcd8c2168959.JPG)

Example of proper displaying of notes:

![note_proper](https://user-images.githubusercontent.com/40228854/44528062-e76b6a00-a6e8-11e8-8b7f-88e614229d01.JPG)

**Comment by openstaxalina** [comment]
@wilkus27 I moved this to the cnx-recipes repo. I think this needs dev analysis before we make this a content-managers issue.

**Comment by PatBoj** [comment]
@openstaxalina In my opinion, it is content, because this note is different from other notes:

:heart: there is `data-element-type="Note"` only in this particular case,
:green_heart: `data-label` is not empty,
:yellow_heart: the title isn't in an additional `div` container,
:purple_heart: content is not in the paragraph `p`.

## ***Wrong:***
![image](https://user-images.githubusercontent.com/20907906/44579907-52c04500-a798-11e8-8fd6-f4f7f0a710fa.png)
![image](https://user-images.githubusercontent.com/20907906/44579911-548a0880-a798-11e8-948f-1fb201fdab87.png)

## ***Right:***
### Example 1:
![image](https://user-images.githubusercontent.com/20907906/44579940-6cfa2300-a798-11e8-9983-091c7a73af72.png)
![image](https://user-images.githubusercontent.com/20907906/44579944-71bed700-a798-11e8-861d-dcd1282feb70.png)

### Example 2:
![image](https://user-images.githubusercontent.com/20907906/44579950-771c2180-a798-11e8-9bff-0fc9dbe90035.png)
![image](https://user-images.githubusercontent.com/20907906/44579954-78e5e500-a798-11e8-86d6-6fbddcfcc9bb.png)

**Comment by openstaxalina** [comment]
Issue moved to [Connexions/content-managers #265](https://github.com/Connexions/content-managers/issues/265) via [**ZenHub**](https://www.zenhub.com/)
