### ISSUE TITLE
Extra header

### ISSUE THREAD

**Issue by openstaxalina** [Connexions/cnx-recipes#576]
@wilkus27 commented on [Thu Aug 23 2018](https://github.com/Connexions/content-managers/issues/257)

On katalyst01 (https://katalyst01.cnx.org/contents/MBiUQmmY@20.1:AY7odN1L@12/5-3-The-Exponential-Distribution -> **Example 5.8**) in box **USING THE CALCULATOR** there is extra header:

![ex_head](https://user-images.githubusercontent.com/40228854/44534947-39b48700-a6f9-11e8-879b-77d2caa20914.JPG)

PDF:

![ex_head_pdf](https://user-images.githubusercontent.com/40228854/44534957-420cc200-a6f9-11e8-9cb1-87d10db4113b.JPG)

**Comment by openstaxalina** [comment]
@wilkus27 I moved this to the cnx-recipes repo. I think this needs dev analysis before we make this a content-managers issue.

**Comment by PatBoj** [comment]
@openstaxalina it looks like the "Collaborative Exercise" title was added by the author, because it exists in raw (not baked) content.

## **With "Collaborative Exercise" title:**
![image](https://user-images.githubusercontent.com/20907906/44581288-6a4dfc80-a79d-11e8-8b96-f86633b9e988.png)
![image](https://user-images.githubusercontent.com/20907906/44581290-6cb05680-a79d-11e8-868e-caf11cdad3e5.png)

## **Without this title:**
![image](https://user-images.githubusercontent.com/20907906/44581302-72a63780-a79d-11e8-8828-e70fd2a5192b.png)
![image](https://user-images.githubusercontent.com/20907906/44581306-76d25500-a79d-11e8-86b9-cbf41a30d9dc.png)

**Comment by openstaxalina** [comment]
Issue moved to [Connexions/content-managers #264](https://github.com/Connexions/content-managers/issues/264) via [**ZenHub**](https://www.zenhub.com/)
