### ISSUE TITLE
Table and figure next to each other

### ISSUE THREAD

**Issue by wilkus27** [Connexions/cnx-recipes#577]
On katalyst01(https://katalyst01.cnx.org/contents/MBiUQmmY@20.1:RIkTUiHP@2/12-2-Scatter-Plots) there is a problem with table and figure which should display next to each other:

![table_fig](https://user-images.githubusercontent.com/40228854/44732359-6abffd80-aae5-11e8-9c58-db1f61e25924.JPG)

This is how it looks in pdf:

![table_fig_pdf](https://user-images.githubusercontent.com/40228854/44732392-76abbf80-aae5-11e8-9a99-27f6f8eddd40.JPG)

Here it also displays incorrectly, because caption of figure is not under the image.

**Comment by PiotrKozlowski** [comment]
There are 2 figures inside figure which is causing some errors in code structure:

- `Figure 12.5` is moved to caption for first of nested figures - next to table caption.
- Caption for image is moved to caption container of parent figure.

- Caption and number for table are in correct container, but there are 2 dividers instead of one
![nested figures](https://user-images.githubusercontent.com/31478212/44732611-f76abb80-aae5-11e8-8a60-f0457d760690.png)

**Comment by openstaxalina** [comment]
We should decide -- in scrum Thursday if not before -- whether this should be fixed in code or content.

**Comment by openstaxalina** [comment]
*Decision:* this will be fixed in content.  @wilkus27 to share the other example she found.  Alina to move this to content-managers.

**Comment by wilkus27** [comment]
Second example: https://katalyst01.cnx.org/contents/MBiUQmmY@20.1:_WBoD9u3@5/12-3-The-Regression-Equation -> **Example 12.6**

**Comment by openstaxalina** [comment]
Issue moved to [Connexions/content-managers #283](https://github.com/Connexions/content-managers/issues/283) via [**ZenHub**](https://www.zenhub.com/)
