### ISSUE TITLE
Box without header

### ISSUE THREAD

**Issue by wilkus27** [Connexions/cnx-recipes#583]
On katalyst01 (https://katalyst01.cnx.org/contents/MBiUQmmY@20.1:Tz_nB1he@6/C-Group-and-Partner-Projects) there are two boxes with header **Examples** 

![example](https://user-images.githubusercontent.com/40228854/44815232-3df01100-abdf-11e8-9733-f9b1e773fd56.JPG)

![example2](https://user-images.githubusercontent.com/40228854/44815241-43e5f200-abdf-11e8-92a1-a6e24293227f.JPG)

In PDF these boxes are without headers:

![example_pdf](https://user-images.githubusercontent.com/40228854/44815280-61b35700-abdf-11e8-8c69-479e00c339fd.JPG)

It looks like it is similar problem to issue https://github.com/Connexions/content-managers/issues/265, but **Example** box should be numbered.

Proper example box:

![example_proper](https://user-images.githubusercontent.com/40228854/44815512-046bd580-abe0-11e8-8a76-3f8f92f67f17.JPG)

I am not sure what was an assumption about these boxes. Should they be numbered or should we create new header **EXAMPLES**?

**Comment by openstaxalina** [comment]
These boxes should not be numbered, since they are not numbered in the PDF.  This would probably be resolved in content, but would be low-priority.  I'll review this issue w/ @helenemccarron and if she agrees it's content, I'll move it to content-managers.

**Comment by helenemccarron** [comment]
The reason those are behaving strangely is because they are generic notes but do not follow generic notes rules: generic notes have a title that is then normalized via the recipes. Currently, we do not support generic notes without a title, because they wouldn't be identifiable without CSS (as per the guidelines we established for content manipulation via recipes)

In the screenshots above, the "examples" are notes without a title and with a `data-label="Examples"`, which Webview uses to display  the final result.

However, those are not supported by the recipes and the "Examples" title will display only in Webview. I recommend to either give the generic notes a title of "note" or give them a class, effectively handling them as specific notes, with a desired title such as "Examples". Either way, we need a title so they can be displayed properly on all platforms.

**Comment by openstaxalina** [comment]
Issue moved to [Connexions/content-managers #294](https://github.com/Connexions/content-managers/issues/294) via [**ZenHub**](https://www.zenhub.com/)
